### ISSUE TITLE
Setting org-mode hook makes RET on roam links stop working

### ISSUE THREAD

**Issue by mediapathic** [NicolasPetton/nroam#20]
Within doom emacs, so I suspect my specific keybinds will be different from vanilla but not the base issue:

When I set 
```
(add-hook 'org-mode-hook #'nroam-setup-maybe)
```
hitting `RET` on roam links emits `evil-ret` instead of `+org/dwim-at-point`, which normally opens links. If I issue `+org/dwim-at-point` the links work fine, so the issue is in the mapping of `RET`. 

Additionally, the nroam text at the bottom of the buffer says 

```
* Backlinks                                                        :noexport:
** 23 linked references
```
But the linked references headline has no children. 

I note that if I activate nroam manually while in a file links still work, but the lack of references remains. The lack of references is perhaps a different issue, but I mention it here just in case it's related. 

This just started happening after I updated to the most recent version, a few days ago. 

Here I must admit that I have a hideously complex and baroque setup, so this is probably nroam interacting poorly with something mysterious somewhere. If there's anything I can do to get a more helpful narrowed down repro, please let me know.

**Comment by NicolasPetton** [comment]
nroam defines a mode-map and binds `RET`, that's why you're seeing this issue. I'll see how we can fix this problem.

**Comment by NicolasPetton** [comment]
@mediapathic I think commit https://github.com/NicolasPetton/nroam/commit/cab2be0102c122a8ef4607a1a12708bcb05b5afd should fix the issue. Could you confirm?

**Comment by mediapathic** [comment]
Initial testing indicates yes! II will use it for a while and confirm that it remains fixed. Thanks!

**Comment by mediapathic** [comment]
@NicolasPetton I've been playing with this and haven't seen any evidence that this bug isn't fixed. I think this can probably be closed. Thank you!
